#! /bin/sh
# slc, a SVP generic compiler.
# Copyright (C) 2009 The CSA group, The SL project.

set -e

if [ "$#" -eq "1" ]; then
  AUTORECONF=$1
  echo "Using \`$1' instead of \`autoreconf' command"
else
  AUTORECONF=autoreconf
fi

sl-init-autoconf

(cd benchmarks/livermore && mkdir -p data && python ./ll-generate.py <ll-bounds.csv)
(cd benchmarks/blas && bash ./gendata.sh)
(cd benchmarks/lib && bash genmake.sh)
$AUTORECONF -v -f -i

echo "Reconfiguration done."
